name: Create and publish a Docker image
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches:  ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@5f4866a30a54f16a52d2ecb4a3898e9e424939cf
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@1294d94f8ee362ab42b6da04c35f4cd03a0e6af7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=semver,pattern={{version}},value=2.315.0
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@7e6f77677b7892794c8852c6e3773c3e9bc3129a
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
